#Server props
spring.application.name=ServerEduShare
server.port=7777

#DB props
spring.datasource.url=jdbc:postgresql://localhost:5432/EduShareDB
spring.datasource.username=EduShareAdmin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect